name: "提交新 Doubao 图片案例 ✨"
description: 分享您发现的精彩 Doubao 图片案例及其提示词，帮助我们丰富案例库！维护者会协助整理收录。
title: "新案例：<请为新案例起一个简短描述性标题，例如：纸艺风格 Emoji>"
labels: ["contribution", "image"]
body:
  - type: markdown
    attributes:
      value: |
        **感谢您分享精彩案例！请尽可能详细地填写以下信息，方便我们收录 👇**

  - type: textarea
    id: preview_image
    attributes:
      label: 请上传或粘贴案例图片
      description: 拖拽或粘贴图片到此处（建议 ≤1 MB）
      placeholder: "将图片文件拖拽到此处或粘贴截图"
    validations:
      required: true

  - type: input
    id: source_link
    attributes:
      label: 案例来源链接
      description: 分享该案例的原帖链接（如推文、博客文章等），用于溯源和致谢。
      placeholder: "https://x.com/xxxx/status/123..."
    validations:
      required: true

  - type: input
    id: author_link
    attributes:
      label: 原作者主页链接
      description: 分享该案例的原作者个人主页（如 Twitter/X、GitHub、个人网站等）
      placeholder: "https://x.com/xxxx"
    validations:
      required: true

  - type: textarea
    id: prompt_cn
    attributes:
      label: 提示词（中文）
      description: 完整中文提示词。最好分别提供中/英文提示词，也可选择其中一种填写（填写一样的即可）
      placeholder: "例如：将图标[🥹]变成充气感靠垫..."
    validations:
      required: true

  - type: textarea
    id: prompt_en
    attributes:
      label: Prompt (English)
      description: 完整英文提示词。最好分别提供中/英文提示词，也可选择其中一种填写（填写一样的即可）
      placeholder: "e.g. Create a paper craft-style '🔥'..."
    validations:
      required: true

  - type: input
    id: prompt_note
    attributes:
      label: 提示词备注(可选)
      description: 关于提示词的额外说明，例如：可替换【括号内】内容。
      placeholder: "例如：提示词中的【XXX】部分可以替换"
    validations:
      required: false

  - type: input
    id: need_reference
    attributes:
      label: 所需参考图说明 (可选)
      description: 如果生成此图需要 **上传参考图片**，请在此说明需要的图片类型（例如：一张单人头像照片）或提供参考图来源。
      placeholder: "例如：需要上传一张人物照片"
    validations:
      required: false
