name: "Submit New Doubao Image Example ✨"
description: "Share an awesome Doubao image example and its prompt you found to help enrich our collection! Maintainers will assist in organizing and adding it."
title: "New Example: <Please provide a short, descriptive title for the example, e.g., New Example: Paper Craft Style Emoji>"
labels: ["contribution", "image"]
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for sharing an awesome example! Please fill out the following information as detailed as possible to help us add it 👇**

  - type: textarea
    id: preview_image
    attributes:
      label: Please upload or paste the example image
      description: "Drag & drop or paste the image here (Recommended ≤1 MB)"
      placeholder: "Drag & drop image file here or paste screenshot"
    validations:
      required: true

  - type: input
    id: source_link
    attributes:
      label: Example Source Link
      description: "Share the link to the original post (e.g., tweet, blog post, etc.) for attribution and reference."
      placeholder: "https://x.com/xxxx/status/123..."
    validations:
      required: true

  - type: input
    id: author_link
    attributes:
      label: Original Author Profile Link
      description: "Share the original author's profile page (e.g., Twitter/X, GitHub, personal website, etc.)"
      placeholder: "https://x.com/xxxx"
    validations:
      required: true

  - type: textarea
    id: prompt_cn
    attributes:
      label: Prompt (Chinese)
      description: "The full Chinese prompt. It's best to provide both Chinese/English prompts if available, but filling in just one is acceptable (just fill in the same if applicable)." # Retained your description logic
      placeholder: "e.g., 将图标[🥹]变成充气感靠垫..." # Example kept in Chinese as per field
    validations:
      required: true

  - type: textarea
    id: prompt_en
    attributes:
      label: Prompt (English)
      description: "The full English prompt. It's best to provide both Chinese/English prompts if available, but filling in just one is acceptable (just fill in the same if applicable)." # Retained your description logic
      placeholder: "e.g. Create a paper craft-style '🔥'..."
    validations:
      required: true

  - type: input
    id: prompt_note
    attributes:
      label: Prompt Notes (Optional)
      description: "Any additional notes about the prompt, e.g., 'Content inside 【brackets】 can be replaced.'"
      placeholder: "e.g., The 【XXX】 part in the prompt can be replaced"
    validations:
      required: false

  - type: input
    id: need_reference
    attributes:
      label: Reference Image Description (Optional)
      description: "If generating this image requires **uploading a reference image**, please describe the type needed (e.g., a single person portrait photo) or provide its source here."
      placeholder: "e.g., Needs a photo of a person"
    validations:
      required: false